# Generated by Django 3.2.8 on 2021-10-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='assets/newsletters')),
                ('target', models.CharField(max_length=50)),
                ('frequency', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(related_name='tags', to='tags.Tags')),
                ('users', models.ManyToManyField(related_name='users', to='users.Users')),
            ],
        ),
    ]
